# starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$env_var\
$line_break\
$time\
$status\
$container\
$character"""


[character]
success_symbol = "[](bold cyan)[](bold green)"
error_symbol = "[](bold red)[](bold red)"

[directory]
format = 'in [$path]($style)[$read_only]($read_only_style) '
style = "bright-magenta bold"
read_only = " "
truncate_to_repo = false

[username]
style_root = 'bold red'
style_user = 'bright-blue bold'
format = '[$user]($style)[@](bright-blue bold)'
show_always = true
disabled = false

[hostname]
format = '[$hostname](bright-blue bold) '
ssh_only = false
disabled = false

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bright-cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = true
added_style = 'bold bright-blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[time]
disabled = false
style = 'bright-cyan'
format = '[\[$time\]]($style) '

[status]
format = '[$symbol$status]($style) '
style = 'bold green'
symbol = '🚀 '

[container]
symbol = "🐳 "
format = "[$symbol$name]($style) "
style = "bright-yellow bold"
